spring.application.name=gestao_vagas
spring.datasource.url=${urlBD}
spring.datasource.username=${userDB}
spring.datasource.password=${passwordDB}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${your-secret-key}