spring.application.name=gestao_vagas
spring.datasource.url=jdbc:postgresql://localhost:5433/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
jwt.secret=3f9bdf9b0f7a4e4a9e4a7a94e9b5c1d4f3a2b1c6e8d7a9c4